apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: "database-1.cy7806ig071x.us-east-1.rds.amazonaws.com"
  DB_USER: "YWRtaW4K"
  DB_PASSWORD: "N3JidXlBcVBjZHB6OHdaVHNpUVkK"
  DB_NAME: "database-1"