apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: mysql:5.7
        envFrom:
          - secretRef:
              name: db-secret
        command: ["sh", "-c"]
        args:
          - |
            echo "Waiting for database to be ready...";
            while ! mysqladmin ping -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" --silent; do
              sleep 5;
            done;
            echo "Initializing database...";
            mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < /sql/schema.sql;
            echo "Database initialized successfully";
        volumeMounts:
        - name: sql-volume
          mountPath: /sql
      volumes:
      - name: sql-volume
        configMap:
          name: schema-sql
      restartPolicy: OnFailure